### ISSUE TITLE
RDoc should use ENV['ProgramFiles'] when looking for hhc.exe

### ISSUE THREAD

**Issue by luislavena** [vertiginous/rdoc_chm#3]
Right now rdoc_chm looks for C:/Program Files/HTML Help Workshop/hhc.exe when it should be using ENV['ProgramFiles']
instead

This issue raises on non-english versions of Windows and also x64 ones, where 32bits tools are installed in different
folders than 64bits.

The following is the way was implemented in RubyInstaller:

  executable = 'hhc.exe'
  path = File.join(ENV['ProgramFiles'], 'HTML Help Workshop', executable)

**Comment by vertiginous** [comment]
Fixed in commit 590cc39c26c3fe271cf08a26f20ad7033aa2a804
