### ISSUE TITLE
Legacy Templates

### ISSUE THREAD

**Issue by Azolo** [vertiginous/rdoc_chm#5]
The templates are still based on RDoc 2.5.x style templates and need to be updated to RDoc 3.12 style templates. (Also some [changes in chm.rb need to be made](https://github.com/rdoc/rdoc/blob/v3.12/lib/rdoc/generator/template/darkfish/class.rhtml#L104-123))

More info: oneclick/rubyinstaller#63

**Comment by luislavena** [comment]
Changes landed in 7e75d21608fcc4440ba8027ff779741ad1e46cf1

Thank you :heart: :heart: :heart:!!!
